### ISSUE TITLE
Cutouts & Measurements have identical RA and Dec ; is this right?

### ISSUE THREAD

**Issue by rknop** [c3-time-domain/SeeChange#259] opened 2024-04-30 20:15 UTC
Is this intended?

What is the meaning in each case?  The x and y of the cutouts is always .00, so it must be the center pixel of the cutout.  I was guessing that the cutout RA and Dec would be the RA and Dec of that center pixel, whereas the measurement ra and dec would be the centroid position of the actual detection.  However, right now the coordinates are identical.  What do they mean in each case?  If the meaning is the same, then we shouldn't have the fields in both tables.

If we're just going to store one, it should be the ra and dec of the centroid of the actual detection.  In that case, the ra and dec should be in the measurements table, but not in the cutouts table.

**Comment by guynir42** [comment] 2024-05-01 05:44
They should have different coordinates. This is on my list...

**Comment by guynir42** [comment] 2024-05-01 05:45
Duplicate of #234

**Closed by guynir42** 2024-05-01 05:45 UTC
