### ISSUE TITLE
Multiprocessing and Session policy

### ISSUE THREAD

**Issue by guynir42** [c3-time-domain/SeeChange#13] opened 2023-03-24 23:58 UTC
It would be really nice if we can come up with a consistent way to manage our sessions (when to open/close them, how many we have open at each point in time). 
This should be built in a way that fits in with our multiprocessing needs (using MPI, I suppose) and fit in with the expected workflows we want to have.

**Comment by rknop** [comment] 2023-03-28 14:13
Do you mean database sessions?

I would, as a general principle say: open a database connection (not just a session, but make sure that SQL Alchmey isn't caching an actual database connection behind somewhere) and close it as soon as you're done with stuff you need to do.  The goal is to keep as few sessions open as possible.

Rationale: if we're running on 60 chips, and then we have (say) 4 nodes each running 60 chips, there will be 240 processes running at once.  Default database limits are of order 100 connections at once.  While we can raise this, we don't want to depend on that.  Things will work better of we explicitly avoid having open database connections hanging around.  This connection bloat happens by *default* with SQL Alchemy, which keeps a connection pool and holds connections open for you.  (You have to use the Null pool to avoid this.)

**Comment by rknop** [comment] 2023-03-28 14:16
As a related thing: one thing I do in *lots* of my functions is pass something like a "curdb" object, which holds the session.  If it's null, the function opens a new session; otherwise, it reuses the existing one.  (The code's not repeated, but I have a "DB" object that holds the session, and it's set up so I can do "with DB.get(curdb) as curdb:" or something like that, so it's simple and pythonic.)  The reason for this is that if you have a database session, and then call a function that itself needs a database session, you'll now have two database connections open at once when you don't really need them.  When I inherited the code from Danny, it was impossible to run more than one exposure at a time, because sometimes multiple connections were open, Danny wasn't anal about closing them, and SQL Alchemy was then polling 2 or more sessions per MPI rank.  This would very quickly use up the number of connections we were allowed at the NERSC database we were using at the time.

I think SQL alchemy's defaults are assuming a use case very different from ours.

**Comment by rknop** [comment] 2023-03-28 18:01
Hmm.... I had a long comment here that I don't see.  I must have forgotten to push the comment button.

In any event, I think this is one of the gigantic design flaws of sqlalchemy.  By encouraging you to work with objects that are magically kept in sync with the background database, it encourages you to keep open database sessions that you don't really need to keep open.

You do need need 250 open database connections to run on 250 cpus at once.  While in principle it's possible, in practice the cores aren't all going to be synced so much that they're hitting the database at once, as the time they spend communicating with the database is a tiny fraction of the time they're running.  Keeping open hundreds of database connections that we don't need open is wasteful, it doesn't scale, and there are eventually performance implications with doing that.  It may also limit use cases for the pipeline where somebody needs to use a database that they don't fully control, and as such needs to have a socially acceptable number of open connections.  So, code needs to open and close database connections as necessary.

And, yes, this does add complications to using sqlalchemy objects, but as I've mentioned before, I'm really not convinced that the code simplifications that using an ORM like sqlalchemy gives you aren't illusory, and ultimately more costly than just understanding and using SQL.   The whole "object detached from session" thing is something that drove me nuts about sqlalchemy until I figured how to work around it (and *not* by insisting that the database server keep open an absurd number of unused connections).  For the most part, I don't have sqlalchemy obejcts live beyond one function.  Of course, sometimes there's a function that returns an sqlachemy object, so, yes, it will live into the calling function.  But by and large I don't save them into (say) the self of objects, and I don't expect them to continue to be valid for long periods of time.  Second, my sessionmaker has "expire_on_commit=False", so that I can keep accessing the fields of a database object even after I've committed it.  Finally, when absolutely necessary, I reconnect a database object to a new session.  Of course, at this point, I'm not working the way sqlalchemy wants me to work... but the way I see the problem is that sqlalchemy isn't using databases the way I'm trying to use databases, so I'm always fighting with it a bit.

I'm not going to give in to a design that throws up our hands and says that the database just has to be able to hold open huge numbers of unused connections.  Connection pooling won't work, because all of the processes opening connection are different processes, so they don't have a way to share a pool.  The solution is just to open the and close the database connection as you need it.

**Comment by guynir42** [comment] 2023-03-28 18:46
I am not 100% sure that the large number of open connections is really a problem. I've never worked on anything that used so many connections, but in principle, if they are mostly idle, there should not be a real issue having them connected all the time. It is like having 250 kids trying to drink from the same fountain: you either make them take turns or you give all of them straws... I'm not sure if there's a difference in efficiency. 

It would reduce a lot of the hassle in our side of the code. So I suggest we check if this is really a problem before we make a design choice. In any case I think we can come up with a design flexible enough that making that change wouldn't be so hard.

**Comment by guynir42** [comment] 2023-03-28 19:31
Reading up on the topic, I see a lot of people recommending not to increase the number of connections... but I think this is misleading, as they are generally talking about servers with a few cores. I think if we have a supercomputer with hundreds of cores, surely we can have a postgres server that can handle more than 100 connections. 

What I see is that each connection takes up 5-10 MB of RAM. That may be a lot for a single machine if you have hundreds of connections, but for NERSC that doesn't seem like a lot.

**Comment by rknop** [comment] 2023-03-28 20:45
Incidentally, before we started renting our own server to run our own database, we used a database that was set up at NERSC.  When I first had danny's code, that never closed sessions, and was overusing the number of connections that were available, I asked the NERSC people to up the number of connections.  They wouldn't do it -- their position (which I now agree with) is that if your code is trying to use that many connections all at once, there's something wrong with your code.

**Comment by guynir42** [comment] 2023-03-29 00:16
Yeah I see that written in a lot of places. There's some underlying truth that more connections require some overhead: https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/analyzing-the-limits-of-connection-scalability-in-postgres/ba-p/1757266 but it doesn't look like 250 is that much worse than 100. 

I get the feeling that "more than 100 connections is too many connections" is a dogma that is more relevant to people running a small app that spawns sessions and leaves them open. Surely if you are running one database and 1000 CPUs that access it would not have a problem giving out more resources to the DB and allowing more than 100 connections. Surely google's servers don't all share 100 connections to their database! If we were running 24 cores, you wouldn't say that having 24 sessions open all the time is bad design. One connection per one CPU core doesn't sound crazy to me. 

On the one hand, I'd like to reduce this load and make it easier to setup, as you say, without additional configuration so it works out of the box. It is also true that most of these sessions would be idle most of the time. 

But let's imagine how this would work: all 250 instances start at the same time and they all need connections. So instead of opening the connections and waiting for the DB to be available they'll be waiting for the connection to start (or it will throw an error, I am not sure what would happen when you reach the maximum connections). 

The alternative is that we open and close sessions, fight against SQLA at every turn, and have all of our cores fighting to get connections all the time.

**Comment by rknop** [comment] 2023-03-29 01:04
There is actually another option, and that is not to use sqlalchemy at all.  (That would probably actually be my preference, except that it means managing database schema migrations becomes much  more manual.)

It's very unlikely for all 250 instances to start at the same time.  You'll probably get 60 starting at the same time -- right now, though, with the way I do it, the start only has one connection, because it starts at the exposure level.  I'm speaking from experience -- I sometimes have 8 lensgrinder jobs running, each with 60 ranks, and the database load stays very mild.  There's no lcoks and no contentions... UNLIKE when the code kept database connections open, and code started failing because the database server didn't want that many connections.

Yes, we're going to have to fight with SA.  We have no choice (if we keep using SA), because SA is designed for people who write web servers who have code sessions that last seconds, not multi-chip data reductions that last minutes.   We are not going to leave database connections sitting open and then have hundreds of idle connections on the database.   We're simply not going to do that.  The software I inherited from Danny did that, and part of the pain of getting it to work for DECAT was undoing that mess.    One connection per CPU constantly open may not sound unreasonable to you, but from experience, it is.

The standard is going to be when we have to communicate with the database, we open a connection, and when we're done, we close it.  We don't hold them open.  It's the only sane way to deal with a shared resource like that.

**Comment by guynir42** [comment] 2023-03-29 03:15
I see you have already been down this path before. Seems to me SQLA is worth keeping around for now, I think we have enough experience with how to fight against it when needed.

**Closed** 2023-03-30 23:31 UTC
Labels: needs decision, architecture
